// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: operations/v1/operations.proto

package operations

import (
	types "github.com/drival-ai/v10-go/types"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for the ListOperations rpc.
type ListOperationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	NextToken     string                 `protobuf:"bytes,2,opt,name=next_token,json=nextToken,proto3" json:"next_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOperationsRequest) Reset() {
	*x = ListOperationsRequest{}
	mi := &file_operations_v1_operations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOperationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOperationsRequest) ProtoMessage() {}

func (x *ListOperationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_operations_v1_operations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOperationsRequest.ProtoReflect.Descriptor instead.
func (*ListOperationsRequest) Descriptor() ([]byte, []int) {
	return file_operations_v1_operations_proto_rawDescGZIP(), []int{0}
}

func (x *ListOperationsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListOperationsRequest) GetNextToken() string {
	if x != nil {
		return x.NextToken
	}
	return ""
}

// Response message for the ListOperations rpc.
type ListOperationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operations    []*types.Operation     `protobuf:"bytes,1,rep,name=operations,proto3" json:"operations,omitempty"`
	NextToken     string                 `protobuf:"bytes,2,opt,name=next_token,json=nextToken,proto3" json:"next_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOperationsResponse) Reset() {
	*x = ListOperationsResponse{}
	mi := &file_operations_v1_operations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOperationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOperationsResponse) ProtoMessage() {}

func (x *ListOperationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_operations_v1_operations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOperationsResponse.ProtoReflect.Descriptor instead.
func (*ListOperationsResponse) Descriptor() ([]byte, []int) {
	return file_operations_v1_operations_proto_rawDescGZIP(), []int{1}
}

func (x *ListOperationsResponse) GetOperations() []*types.Operation {
	if x != nil {
		return x.Operations
	}
	return nil
}

func (x *ListOperationsResponse) GetNextToken() string {
	if x != nil {
		return x.NextToken
	}
	return ""
}

// Request message for the GetOperation rpc.
type GetOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperationRequest) Reset() {
	*x = GetOperationRequest{}
	mi := &file_operations_v1_operations_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperationRequest) ProtoMessage() {}

func (x *GetOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_operations_v1_operations_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperationRequest.ProtoReflect.Descriptor instead.
func (*GetOperationRequest) Descriptor() ([]byte, []int) {
	return file_operations_v1_operations_proto_rawDescGZIP(), []int{2}
}

func (x *GetOperationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Request message for the DeleteOperation rpc.
type DeleteOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOperationRequest) Reset() {
	*x = DeleteOperationRequest{}
	mi := &file_operations_v1_operations_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOperationRequest) ProtoMessage() {}

func (x *DeleteOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_operations_v1_operations_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOperationRequest.ProtoReflect.Descriptor instead.
func (*DeleteOperationRequest) Descriptor() ([]byte, []int) {
	return file_operations_v1_operations_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteOperationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Request message for the CancelOperation rpc.
type CancelOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOperationRequest) Reset() {
	*x = CancelOperationRequest{}
	mi := &file_operations_v1_operations_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOperationRequest) ProtoMessage() {}

func (x *CancelOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_operations_v1_operations_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOperationRequest.ProtoReflect.Descriptor instead.
func (*CancelOperationRequest) Descriptor() ([]byte, []int) {
	return file_operations_v1_operations_proto_rawDescGZIP(), []int{4}
}

func (x *CancelOperationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Request message for the WaitOperation rpc.
type WaitOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitOperationRequest) Reset() {
	*x = WaitOperationRequest{}
	mi := &file_operations_v1_operations_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitOperationRequest) ProtoMessage() {}

func (x *WaitOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_operations_v1_operations_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitOperationRequest.ProtoReflect.Descriptor instead.
func (*WaitOperationRequest) Descriptor() ([]byte, []int) {
	return file_operations_v1_operations_proto_rawDescGZIP(), []int{5}
}

func (x *WaitOperationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_operations_v1_operations_proto protoreflect.FileDescriptor

const file_operations_v1_operations_proto_rawDesc = "" +
	"\n" +
	"\x1eoperations/v1/operations.proto\x12\x16v10proto.operations.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x15types/operation.proto\"J\n" +
	"\x15ListOperationsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"next_token\x18\x02 \x01(\tR\tnextToken\"r\n" +
	"\x16ListOperationsResponse\x129\n" +
	"\n" +
	"operations\x18\x01 \x03(\v2\x19.v10proto.types.OperationR\n" +
	"operations\x12\x1d\n" +
	"\n" +
	"next_token\x18\x02 \x01(\tR\tnextToken\")\n" +
	"\x13GetOperationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\",\n" +
	"\x16DeleteOperationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\",\n" +
	"\x16CancelOperationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"*\n" +
	"\x14WaitOperationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name2\x83\x06\n" +
	"\n" +
	"Operations\x12\x84\x01\n" +
	"\x0eListOperations\x12-.v10proto.operations.v1.ListOperationsRequest\x1a..v10proto.operations.v1.ListOperationsResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/v10/ops/v1\x12r\n" +
	"\fGetOperation\x12+.v10proto.operations.v1.GetOperationRequest\x1a\x19.v10proto.types.Operation\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v10/ops/v1/{name}\x12u\n" +
	"\x0fDeleteOperation\x12..v10proto.operations.v1.DeleteOperationRequest\x1a\x16.google.protobuf.Empty\"\x1a\x82\xd3\xe4\x93\x02\x14*\x12/v10/ops/v1/{name}\x12\x7f\n" +
	"\x0fCancelOperation\x12..v10proto.operations.v1.CancelOperationRequest\x1a\x16.google.protobuf.Empty\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v10/ops/v1/{name}:cancel\x12Z\n" +
	"\rWaitOperation\x12,.v10proto.operations.v1.WaitOperationRequest\x1a\x19.v10proto.types.Operation\"\x00\x1a\xa5\x01\x92A\xa1\x01\x127(ALPHA) Operations API. Base URL: https://api.drival.ai\x1af\n" +
	"$See here for the service definition.\x12>https://github.com/drival-ai/v10-proto/tree/main/operations/v1B(Z&github.com/drival-ai/v10-go/operationsb\x06proto3"

var (
	file_operations_v1_operations_proto_rawDescOnce sync.Once
	file_operations_v1_operations_proto_rawDescData []byte
)

func file_operations_v1_operations_proto_rawDescGZIP() []byte {
	file_operations_v1_operations_proto_rawDescOnce.Do(func() {
		file_operations_v1_operations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_operations_v1_operations_proto_rawDesc), len(file_operations_v1_operations_proto_rawDesc)))
	})
	return file_operations_v1_operations_proto_rawDescData
}

var file_operations_v1_operations_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_operations_v1_operations_proto_goTypes = []any{
	(*ListOperationsRequest)(nil),  // 0: v10proto.operations.v1.ListOperationsRequest
	(*ListOperationsResponse)(nil), // 1: v10proto.operations.v1.ListOperationsResponse
	(*GetOperationRequest)(nil),    // 2: v10proto.operations.v1.GetOperationRequest
	(*DeleteOperationRequest)(nil), // 3: v10proto.operations.v1.DeleteOperationRequest
	(*CancelOperationRequest)(nil), // 4: v10proto.operations.v1.CancelOperationRequest
	(*WaitOperationRequest)(nil),   // 5: v10proto.operations.v1.WaitOperationRequest
	(*types.Operation)(nil),        // 6: v10proto.types.Operation
	(*emptypb.Empty)(nil),          // 7: google.protobuf.Empty
}
var file_operations_v1_operations_proto_depIdxs = []int32{
	6, // 0: v10proto.operations.v1.ListOperationsResponse.operations:type_name -> v10proto.types.Operation
	0, // 1: v10proto.operations.v1.Operations.ListOperations:input_type -> v10proto.operations.v1.ListOperationsRequest
	2, // 2: v10proto.operations.v1.Operations.GetOperation:input_type -> v10proto.operations.v1.GetOperationRequest
	3, // 3: v10proto.operations.v1.Operations.DeleteOperation:input_type -> v10proto.operations.v1.DeleteOperationRequest
	4, // 4: v10proto.operations.v1.Operations.CancelOperation:input_type -> v10proto.operations.v1.CancelOperationRequest
	5, // 5: v10proto.operations.v1.Operations.WaitOperation:input_type -> v10proto.operations.v1.WaitOperationRequest
	1, // 6: v10proto.operations.v1.Operations.ListOperations:output_type -> v10proto.operations.v1.ListOperationsResponse
	6, // 7: v10proto.operations.v1.Operations.GetOperation:output_type -> v10proto.types.Operation
	7, // 8: v10proto.operations.v1.Operations.DeleteOperation:output_type -> google.protobuf.Empty
	7, // 9: v10proto.operations.v1.Operations.CancelOperation:output_type -> google.protobuf.Empty
	6, // 10: v10proto.operations.v1.Operations.WaitOperation:output_type -> v10proto.types.Operation
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_operations_v1_operations_proto_init() }
func file_operations_v1_operations_proto_init() {
	if File_operations_v1_operations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_operations_v1_operations_proto_rawDesc), len(file_operations_v1_operations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_operations_v1_operations_proto_goTypes,
		DependencyIndexes: file_operations_v1_operations_proto_depIdxs,
		MessageInfos:      file_operations_v1_operations_proto_msgTypes,
	}.Build()
	File_operations_v1_operations_proto = out.File
	file_operations_v1_operations_proto_goTypes = nil
	file_operations_v1_operations_proto_depIdxs = nil
}
