// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: types/cloud.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Location struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If set, prioritize over active region.
	ActiveZone string `protobuf:"bytes,1,opt,name=active_zone,json=activeZone,proto3" json:"active_zone,omitempty"`
	// Valid only when active zone is not set.
	ActiveRegion string `protobuf:"bytes,2,opt,name=active_region,json=activeRegion,proto3" json:"active_region,omitempty"`
	// If set, prioritize over passive region.
	PassiveZone string `protobuf:"bytes,3,opt,name=passive_zone,json=passiveZone,proto3" json:"passive_zone,omitempty"`
	// Valid only when passive zone is not set.
	PassiveRegion string `protobuf:"bytes,4,opt,name=passive_region,json=passiveRegion,proto3" json:"passive_region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_types_cloud_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_types_cloud_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_types_cloud_proto_rawDescGZIP(), []int{0}
}

func (x *Location) GetActiveZone() string {
	if x != nil {
		return x.ActiveZone
	}
	return ""
}

func (x *Location) GetActiveRegion() string {
	if x != nil {
		return x.ActiveRegion
	}
	return ""
}

func (x *Location) GetPassiveZone() string {
	if x != nil {
		return x.PassiveZone
	}
	return ""
}

func (x *Location) GetPassiveRegion() string {
	if x != nil {
		return x.PassiveRegion
	}
	return ""
}

type GCPInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServiceAccount []byte                 `protobuf:"bytes,1,opt,name=service_account,json=serviceAccount,proto3" json:"service_account,omitempty"`
	Location       *Location              `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GCPInfo) Reset() {
	*x = GCPInfo{}
	mi := &file_types_cloud_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GCPInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GCPInfo) ProtoMessage() {}

func (x *GCPInfo) ProtoReflect() protoreflect.Message {
	mi := &file_types_cloud_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GCPInfo.ProtoReflect.Descriptor instead.
func (*GCPInfo) Descriptor() ([]byte, []int) {
	return file_types_cloud_proto_rawDescGZIP(), []int{1}
}

func (x *GCPInfo) GetServiceAccount() []byte {
	if x != nil {
		return x.ServiceAccount
	}
	return nil
}

func (x *GCPInfo) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

type AWSInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Prioritized over id/secret.
	RoleArn       string    `protobuf:"bytes,1,opt,name=role_arn,json=roleArn,proto3" json:"role_arn,omitempty"`
	ClientIdArn   string    `protobuf:"bytes,2,opt,name=client_id_arn,json=clientIdArn,proto3" json:"client_id_arn,omitempty"`
	ClientSecret  string    `protobuf:"bytes,3,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	Location      *Location `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AWSInfo) Reset() {
	*x = AWSInfo{}
	mi := &file_types_cloud_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AWSInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AWSInfo) ProtoMessage() {}

func (x *AWSInfo) ProtoReflect() protoreflect.Message {
	mi := &file_types_cloud_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AWSInfo.ProtoReflect.Descriptor instead.
func (*AWSInfo) Descriptor() ([]byte, []int) {
	return file_types_cloud_proto_rawDescGZIP(), []int{2}
}

func (x *AWSInfo) GetRoleArn() string {
	if x != nil {
		return x.RoleArn
	}
	return ""
}

func (x *AWSInfo) GetClientIdArn() string {
	if x != nil {
		return x.ClientIdArn
	}
	return ""
}

func (x *AWSInfo) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *AWSInfo) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

type AzureInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AzureInfo) Reset() {
	*x = AzureInfo{}
	mi := &file_types_cloud_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AzureInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AzureInfo) ProtoMessage() {}

func (x *AzureInfo) ProtoReflect() protoreflect.Message {
	mi := &file_types_cloud_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AzureInfo.ProtoReflect.Descriptor instead.
func (*AzureInfo) Descriptor() ([]byte, []int) {
	return file_types_cloud_proto_rawDescGZIP(), []int{3}
}

var File_types_cloud_proto protoreflect.FileDescriptor

const file_types_cloud_proto_rawDesc = "" +
	"\n" +
	"\x11types/cloud.proto\x12\x0ev10proto.types\"\x9a\x01\n" +
	"\bLocation\x12\x1f\n" +
	"\vactive_zone\x18\x01 \x01(\tR\n" +
	"activeZone\x12#\n" +
	"\ractive_region\x18\x02 \x01(\tR\factiveRegion\x12!\n" +
	"\fpassive_zone\x18\x03 \x01(\tR\vpassiveZone\x12%\n" +
	"\x0epassive_region\x18\x04 \x01(\tR\rpassiveRegion\"h\n" +
	"\aGCPInfo\x12'\n" +
	"\x0fservice_account\x18\x01 \x01(\fR\x0eserviceAccount\x124\n" +
	"\blocation\x18\x02 \x01(\v2\x18.v10proto.types.LocationR\blocation\"\xa3\x01\n" +
	"\aAWSInfo\x12\x19\n" +
	"\brole_arn\x18\x01 \x01(\tR\aroleArn\x12\"\n" +
	"\rclient_id_arn\x18\x02 \x01(\tR\vclientIdArn\x12#\n" +
	"\rclient_secret\x18\x03 \x01(\tR\fclientSecret\x124\n" +
	"\blocation\x18\x04 \x01(\v2\x18.v10proto.types.LocationR\blocation\"\v\n" +
	"\tAzureInfoB#Z!github.com/drival-ai/v10-go/typesb\x06proto3"

var (
	file_types_cloud_proto_rawDescOnce sync.Once
	file_types_cloud_proto_rawDescData []byte
)

func file_types_cloud_proto_rawDescGZIP() []byte {
	file_types_cloud_proto_rawDescOnce.Do(func() {
		file_types_cloud_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_cloud_proto_rawDesc), len(file_types_cloud_proto_rawDesc)))
	})
	return file_types_cloud_proto_rawDescData
}

var file_types_cloud_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_types_cloud_proto_goTypes = []any{
	(*Location)(nil),  // 0: v10proto.types.Location
	(*GCPInfo)(nil),   // 1: v10proto.types.GCPInfo
	(*AWSInfo)(nil),   // 2: v10proto.types.AWSInfo
	(*AzureInfo)(nil), // 3: v10proto.types.AzureInfo
}
var file_types_cloud_proto_depIdxs = []int32{
	0, // 0: v10proto.types.GCPInfo.location:type_name -> v10proto.types.Location
	0, // 1: v10proto.types.AWSInfo.location:type_name -> v10proto.types.Location
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_types_cloud_proto_init() }
func file_types_cloud_proto_init() {
	if File_types_cloud_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_cloud_proto_rawDesc), len(file_types_cloud_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_cloud_proto_goTypes,
		DependencyIndexes: file_types_cloud_proto_depIdxs,
		MessageInfos:      file_types_cloud_proto_msgTypes,
	}.Build()
	File_types_cloud_proto = out.File
	file_types_cloud_proto_goTypes = nil
	file_types_cloud_proto_depIdxs = nil
}
