// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: base/v1/v10.proto

package base

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Vehicle message definition.
type Vehicle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vin           string                 `protobuf:"bytes,1,opt,name=vin,proto3" json:"vin,omitempty"`
	Make          string                 `protobuf:"bytes,2,opt,name=make,proto3" json:"make,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Year          int32                  `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
	Kilometers    int32                  `protobuf:"varint,5,opt,name=kilometers,proto3" json:"kilometers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vehicle) Reset() {
	*x = Vehicle{}
	mi := &file_base_v1_v10_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vehicle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vehicle) ProtoMessage() {}

func (x *Vehicle) ProtoReflect() protoreflect.Message {
	mi := &file_base_v1_v10_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vehicle.ProtoReflect.Descriptor instead.
func (*Vehicle) Descriptor() ([]byte, []int) {
	return file_base_v1_v10_proto_rawDescGZIP(), []int{0}
}

func (x *Vehicle) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

func (x *Vehicle) GetMake() string {
	if x != nil {
		return x.Make
	}
	return ""
}

func (x *Vehicle) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Vehicle) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Vehicle) GetKilometers() int32 {
	if x != nil {
		return x.Kilometers
	}
	return 0
}

// Request message for the RegisterVehicle rpc.
type RegisterVehicleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vehicle       *Vehicle               `protobuf:"bytes,1,opt,name=vehicle,proto3" json:"vehicle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterVehicleRequest) Reset() {
	*x = RegisterVehicleRequest{}
	mi := &file_base_v1_v10_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterVehicleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterVehicleRequest) ProtoMessage() {}

func (x *RegisterVehicleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_base_v1_v10_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterVehicleRequest.ProtoReflect.Descriptor instead.
func (*RegisterVehicleRequest) Descriptor() ([]byte, []int) {
	return file_base_v1_v10_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterVehicleRequest) GetVehicle() *Vehicle {
	if x != nil {
		return x.Vehicle
	}
	return nil
}

// Request message for the RegisterVehicle rpc.
type ListVehiclesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVehiclesRequest) Reset() {
	*x = ListVehiclesRequest{}
	mi := &file_base_v1_v10_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVehiclesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVehiclesRequest) ProtoMessage() {}

func (x *ListVehiclesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_base_v1_v10_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVehiclesRequest.ProtoReflect.Descriptor instead.
func (*ListVehiclesRequest) Descriptor() ([]byte, []int) {
	return file_base_v1_v10_proto_rawDescGZIP(), []int{2}
}

// Response message for the ListVehicles rpc.
type ListVehiclesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vehicles      []*Vehicle             `protobuf:"bytes,1,rep,name=vehicles,proto3" json:"vehicles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVehiclesResponse) Reset() {
	*x = ListVehiclesResponse{}
	mi := &file_base_v1_v10_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVehiclesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVehiclesResponse) ProtoMessage() {}

func (x *ListVehiclesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_base_v1_v10_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVehiclesResponse.ProtoReflect.Descriptor instead.
func (*ListVehiclesResponse) Descriptor() ([]byte, []int) {
	return file_base_v1_v10_proto_rawDescGZIP(), []int{3}
}

func (x *ListVehiclesResponse) GetVehicles() []*Vehicle {
	if x != nil {
		return x.Vehicles
	}
	return nil
}

type DeleteVehicleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Vehicle Identification Number (VIN) to delete.
	Vin           string `protobuf:"bytes,1,opt,name=vin,proto3" json:"vin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVehicleRequest) Reset() {
	*x = DeleteVehicleRequest{}
	mi := &file_base_v1_v10_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVehicleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVehicleRequest) ProtoMessage() {}

func (x *DeleteVehicleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_base_v1_v10_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVehicleRequest.ProtoReflect.Descriptor instead.
func (*DeleteVehicleRequest) Descriptor() ([]byte, []int) {
	return file_base_v1_v10_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteVehicleRequest) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

type UpdateVehicleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Vehicle Identification Number (VIN) to update.
	Vin string `protobuf:"bytes,1,opt,name=vin,proto3" json:"vin,omitempty"`
	// Required. Vehicle data.
	Vehicle       *Vehicle `protobuf:"bytes,2,opt,name=vehicle,proto3" json:"vehicle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVehicleRequest) Reset() {
	*x = UpdateVehicleRequest{}
	mi := &file_base_v1_v10_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVehicleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVehicleRequest) ProtoMessage() {}

func (x *UpdateVehicleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_base_v1_v10_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVehicleRequest.ProtoReflect.Descriptor instead.
func (*UpdateVehicleRequest) Descriptor() ([]byte, []int) {
	return file_base_v1_v10_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateVehicleRequest) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

func (x *UpdateVehicleRequest) GetVehicle() *Vehicle {
	if x != nil {
		return x.Vehicle
	}
	return nil
}

type UserMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Rank          string                 `protobuf:"bytes,2,opt,name=rank,proto3" json:"rank,omitempty"`
	Points        int32                  `protobuf:"varint,3,opt,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserMetadata) Reset() {
	*x = UserMetadata{}
	mi := &file_base_v1_v10_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMetadata) ProtoMessage() {}

func (x *UserMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_base_v1_v10_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMetadata.ProtoReflect.Descriptor instead.
func (*UserMetadata) Descriptor() ([]byte, []int) {
	return file_base_v1_v10_proto_rawDescGZIP(), []int{6}
}

func (x *UserMetadata) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserMetadata) GetRank() string {
	if x != nil {
		return x.Rank
	}
	return ""
}

func (x *UserMetadata) GetPoints() int32 {
	if x != nil {
		return x.Points
	}
	return 0
}

type UpdateUserMetadataRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. User ID to update.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Required. User metadata.
	UserMetadata  *UserMetadata `protobuf:"bytes,2,opt,name=userMetadata,proto3" json:"userMetadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserMetadataRequest) Reset() {
	*x = UpdateUserMetadataRequest{}
	mi := &file_base_v1_v10_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserMetadataRequest) ProtoMessage() {}

func (x *UpdateUserMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_base_v1_v10_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserMetadataRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserMetadataRequest) Descriptor() ([]byte, []int) {
	return file_base_v1_v10_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateUserMetadataRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateUserMetadataRequest) GetUserMetadata() *UserMetadata {
	if x != nil {
		return x.UserMetadata
	}
	return nil
}

type CreateTripRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Vehicle Identification Number (VIN) to be used for the trip.
	Vin string `protobuf:"bytes,1,opt,name=vin,proto3" json:"vin,omitempty"`
	// Required. Start time of the trip
	StartTime     string `protobuf:"bytes,2,opt,name=startTime,proto3" json:"startTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTripRequest) Reset() {
	*x = CreateTripRequest{}
	mi := &file_base_v1_v10_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTripRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTripRequest) ProtoMessage() {}

func (x *CreateTripRequest) ProtoReflect() protoreflect.Message {
	mi := &file_base_v1_v10_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTripRequest.ProtoReflect.Descriptor instead.
func (*CreateTripRequest) Descriptor() ([]byte, []int) {
	return file_base_v1_v10_proto_rawDescGZIP(), []int{8}
}

func (x *CreateTripRequest) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

func (x *CreateTripRequest) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

// Request message for the Do rpc.
type DoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoRequest) Reset() {
	*x = DoRequest{}
	mi := &file_base_v1_v10_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoRequest) ProtoMessage() {}

func (x *DoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_base_v1_v10_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoRequest.ProtoReflect.Descriptor instead.
func (*DoRequest) Descriptor() ([]byte, []int) {
	return file_base_v1_v10_proto_rawDescGZIP(), []int{9}
}

func (x *DoRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// Response message for the Do rpc.
type DoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoResponse) Reset() {
	*x = DoResponse{}
	mi := &file_base_v1_v10_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoResponse) ProtoMessage() {}

func (x *DoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_base_v1_v10_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoResponse.ProtoReflect.Descriptor instead.
func (*DoResponse) Descriptor() ([]byte, []int) {
	return file_base_v1_v10_proto_rawDescGZIP(), []int{10}
}

func (x *DoResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_base_v1_v10_proto protoreflect.FileDescriptor

const file_base_v1_v10_proto_rawDesc = "" +
	"\n" +
	"\x11base/v1/v10.proto\x12\x10v10proto.base.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"y\n" +
	"\aVehicle\x12\x10\n" +
	"\x03vin\x18\x01 \x01(\tR\x03vin\x12\x12\n" +
	"\x04make\x18\x02 \x01(\tR\x04make\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x12\n" +
	"\x04year\x18\x04 \x01(\x05R\x04year\x12\x1e\n" +
	"\n" +
	"kilometers\x18\x05 \x01(\x05R\n" +
	"kilometers\"M\n" +
	"\x16RegisterVehicleRequest\x123\n" +
	"\avehicle\x18\x01 \x01(\v2\x19.v10proto.base.v1.VehicleR\avehicle\"\x15\n" +
	"\x13ListVehiclesRequest\"M\n" +
	"\x14ListVehiclesResponse\x125\n" +
	"\bvehicles\x18\x01 \x03(\v2\x19.v10proto.base.v1.VehicleR\bvehicles\"(\n" +
	"\x14DeleteVehicleRequest\x12\x10\n" +
	"\x03vin\x18\x01 \x01(\tR\x03vin\"]\n" +
	"\x14UpdateVehicleRequest\x12\x10\n" +
	"\x03vin\x18\x01 \x01(\tR\x03vin\x123\n" +
	"\avehicle\x18\x02 \x01(\v2\x19.v10proto.base.v1.VehicleR\avehicle\"J\n" +
	"\fUserMetadata\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04rank\x18\x02 \x01(\tR\x04rank\x12\x16\n" +
	"\x06points\x18\x03 \x01(\x05R\x06points\"o\n" +
	"\x19UpdateUserMetadataRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12B\n" +
	"\fuserMetadata\x18\x02 \x01(\v2\x1e.v10proto.base.v1.UserMetadataR\fuserMetadata\"C\n" +
	"\x11CreateTripRequest\x12\x10\n" +
	"\x03vin\x18\x01 \x01(\tR\x03vin\x12\x1c\n" +
	"\tstartTime\x18\x02 \x01(\tR\tstartTime\"\x1f\n" +
	"\tDoRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\" \n" +
	"\n" +
	"DoResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data2\xa9\a\n" +
	"\x03V10\x12V\n" +
	"\x02Do\x12\x1b.v10proto.base.v1.DoRequest\x1a\x1c.v10proto.base.v1.DoResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v10/v1:do\x12u\n" +
	"\x0fRegisterVehicle\x12(.v10proto.base.v1.RegisterVehicleRequest\x1a\x16.google.protobuf.Empty\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v10/vehicle/register\x12x\n" +
	"\fListVehicles\x12%.v10proto.base.v1.ListVehiclesRequest\x1a&.v10proto.base.v1.ListVehiclesResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v10/vehicle/list\x12k\n" +
	"\rDeleteVehicle\x12&.v10proto.base.v1.DeleteVehicleRequest\x1a\x16.google.protobuf.Empty\"\x1a\x82\xd3\xe4\x93\x02\x14*\x12/v10/vehicle/{vin}\x12n\n" +
	"\rUpdateVehicle\x12&.v10proto.base.v1.UpdateVehicleRequest\x1a\x16.google.protobuf.Empty\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\x1a\x12/v10/vehicle/{vin}\x12|\n" +
	"\x12UpdateUserMetadata\x12+.v10proto.base.v1.UpdateUserMetadataRequest\x1a\x16.google.protobuf.Empty\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\x1a\x16/v10/usermetadata/{id}\x12d\n" +
	"\tStartTrip\x12#.v10proto.base.v1.CreateTripRequest\x1a\x16.google.protobuf.Empty\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v10/trip/start\x1a\x97\x01\x92A\x93\x01\x120(ALPHA) V10 API. Base URL: https://api.drival.ai\x1a_\n" +
	"$See here for the service definition.\x127https://github.com/drival-ai/v10-proto/tree/main/v10/v1B\xbc\x05\x92A\x96\x05\x12\x81\x05\n" +
	"\x11V10 API reference\x12\xe4\x04Drival AI's **V10** API is a RESTful API that can be accessed by an HTTP client such as `curl`, or any HTTP library which is part of most modern programming languages. This API reference is autogenerated from [protocol buffers](https://developers.google.com/protocol-buffers) defined in this [repository](https://github.com/drival-ai/v10-proto).\n" +
	"\n" +
	"Some endpoints, especially those that return lists of resources, have streaming responses; newline-separated stream of “chunks”. Each chunk is an envelope that can contain either a response message or an error. Only the last chunk will include an error, if any.2\x05alpha\x1a\rapi.drival.ai*\x01\x02Z github.com/drival-ai/v10-go/baseb\x06proto3"

var (
	file_base_v1_v10_proto_rawDescOnce sync.Once
	file_base_v1_v10_proto_rawDescData []byte
)

func file_base_v1_v10_proto_rawDescGZIP() []byte {
	file_base_v1_v10_proto_rawDescOnce.Do(func() {
		file_base_v1_v10_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_base_v1_v10_proto_rawDesc), len(file_base_v1_v10_proto_rawDesc)))
	})
	return file_base_v1_v10_proto_rawDescData
}

var file_base_v1_v10_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_base_v1_v10_proto_goTypes = []any{
	(*Vehicle)(nil),                   // 0: v10proto.base.v1.Vehicle
	(*RegisterVehicleRequest)(nil),    // 1: v10proto.base.v1.RegisterVehicleRequest
	(*ListVehiclesRequest)(nil),       // 2: v10proto.base.v1.ListVehiclesRequest
	(*ListVehiclesResponse)(nil),      // 3: v10proto.base.v1.ListVehiclesResponse
	(*DeleteVehicleRequest)(nil),      // 4: v10proto.base.v1.DeleteVehicleRequest
	(*UpdateVehicleRequest)(nil),      // 5: v10proto.base.v1.UpdateVehicleRequest
	(*UserMetadata)(nil),              // 6: v10proto.base.v1.UserMetadata
	(*UpdateUserMetadataRequest)(nil), // 7: v10proto.base.v1.UpdateUserMetadataRequest
	(*CreateTripRequest)(nil),         // 8: v10proto.base.v1.CreateTripRequest
	(*DoRequest)(nil),                 // 9: v10proto.base.v1.DoRequest
	(*DoResponse)(nil),                // 10: v10proto.base.v1.DoResponse
	(*emptypb.Empty)(nil),             // 11: google.protobuf.Empty
}
var file_base_v1_v10_proto_depIdxs = []int32{
	0,  // 0: v10proto.base.v1.RegisterVehicleRequest.vehicle:type_name -> v10proto.base.v1.Vehicle
	0,  // 1: v10proto.base.v1.ListVehiclesResponse.vehicles:type_name -> v10proto.base.v1.Vehicle
	0,  // 2: v10proto.base.v1.UpdateVehicleRequest.vehicle:type_name -> v10proto.base.v1.Vehicle
	6,  // 3: v10proto.base.v1.UpdateUserMetadataRequest.userMetadata:type_name -> v10proto.base.v1.UserMetadata
	9,  // 4: v10proto.base.v1.V10.Do:input_type -> v10proto.base.v1.DoRequest
	1,  // 5: v10proto.base.v1.V10.RegisterVehicle:input_type -> v10proto.base.v1.RegisterVehicleRequest
	2,  // 6: v10proto.base.v1.V10.ListVehicles:input_type -> v10proto.base.v1.ListVehiclesRequest
	4,  // 7: v10proto.base.v1.V10.DeleteVehicle:input_type -> v10proto.base.v1.DeleteVehicleRequest
	5,  // 8: v10proto.base.v1.V10.UpdateVehicle:input_type -> v10proto.base.v1.UpdateVehicleRequest
	7,  // 9: v10proto.base.v1.V10.UpdateUserMetadata:input_type -> v10proto.base.v1.UpdateUserMetadataRequest
	8,  // 10: v10proto.base.v1.V10.StartTrip:input_type -> v10proto.base.v1.CreateTripRequest
	10, // 11: v10proto.base.v1.V10.Do:output_type -> v10proto.base.v1.DoResponse
	11, // 12: v10proto.base.v1.V10.RegisterVehicle:output_type -> google.protobuf.Empty
	3,  // 13: v10proto.base.v1.V10.ListVehicles:output_type -> v10proto.base.v1.ListVehiclesResponse
	11, // 14: v10proto.base.v1.V10.DeleteVehicle:output_type -> google.protobuf.Empty
	11, // 15: v10proto.base.v1.V10.UpdateVehicle:output_type -> google.protobuf.Empty
	11, // 16: v10proto.base.v1.V10.UpdateUserMetadata:output_type -> google.protobuf.Empty
	11, // 17: v10proto.base.v1.V10.StartTrip:output_type -> google.protobuf.Empty
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_base_v1_v10_proto_init() }
func file_base_v1_v10_proto_init() {
	if File_base_v1_v10_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_base_v1_v10_proto_rawDesc), len(file_base_v1_v10_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_base_v1_v10_proto_goTypes,
		DependencyIndexes: file_base_v1_v10_proto_depIdxs,
		MessageInfos:      file_base_v1_v10_proto_msgTypes,
	}.Build()
	File_base_v1_v10_proto = out.File
	file_base_v1_v10_proto_goTypes = nil
	file_base_v1_v10_proto_depIdxs = nil
}
