// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             (unknown)
// source: base/v1/v10.proto

package base

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	V10_Do_FullMethodName              = "/v10proto.base.v1.V10/Do"
	V10_RegisterVehicle_FullMethodName = "/v10proto.base.v1.V10/RegisterVehicle"
)

// V10Client is the client API for V10 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// V10 service definition.
type V10Client interface {
	// Testing endpoint.
	Do(ctx context.Context, in *DoRequest, opts ...grpc.CallOption) (*DoResponse, error)
	RegisterVehicle(ctx context.Context, in *RegisterVehicleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type v10Client struct {
	cc grpc.ClientConnInterface
}

func NewV10Client(cc grpc.ClientConnInterface) V10Client {
	return &v10Client{cc}
}

func (c *v10Client) Do(ctx context.Context, in *DoRequest, opts ...grpc.CallOption) (*DoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DoResponse)
	err := c.cc.Invoke(ctx, V10_Do_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *v10Client) RegisterVehicle(ctx context.Context, in *RegisterVehicleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, V10_RegisterVehicle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// V10Server is the server API for V10 service.
// All implementations must embed UnimplementedV10Server
// for forward compatibility
//
// V10 service definition.
type V10Server interface {
	// Testing endpoint.
	Do(context.Context, *DoRequest) (*DoResponse, error)
	RegisterVehicle(context.Context, *RegisterVehicleRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedV10Server()
}

// UnimplementedV10Server must be embedded to have forward compatible implementations.
type UnimplementedV10Server struct {
}

func (UnimplementedV10Server) Do(context.Context, *DoRequest) (*DoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Do not implemented")
}
func (UnimplementedV10Server) RegisterVehicle(context.Context, *RegisterVehicleRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterVehicle not implemented")
}
func (UnimplementedV10Server) mustEmbedUnimplementedV10Server() {}

// UnsafeV10Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to V10Server will
// result in compilation errors.
type UnsafeV10Server interface {
	mustEmbedUnimplementedV10Server()
}

func RegisterV10Server(s grpc.ServiceRegistrar, srv V10Server) {
	s.RegisterService(&V10_ServiceDesc, srv)
}

func _V10_Do_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(V10Server).Do(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: V10_Do_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(V10Server).Do(ctx, req.(*DoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _V10_RegisterVehicle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterVehicleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(V10Server).RegisterVehicle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: V10_RegisterVehicle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(V10Server).RegisterVehicle(ctx, req.(*RegisterVehicleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// V10_ServiceDesc is the grpc.ServiceDesc for V10 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var V10_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v10proto.base.v1.V10",
	HandlerType: (*V10Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Do",
			Handler:    _V10_Do_Handler,
		},
		{
			MethodName: "RegisterVehicle",
			Handler:    _V10_RegisterVehicle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "base/v1/v10.proto",
}
