// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             (unknown)
// source: base/v1/v10.proto

package base

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	V10_Do_FullMethodName                 = "/v10proto.base.v1.V10/Do"
	V10_RegisterVehicle_FullMethodName    = "/v10proto.base.v1.V10/RegisterVehicle"
	V10_ListVehicles_FullMethodName       = "/v10proto.base.v1.V10/ListVehicles"
	V10_DeleteVehicle_FullMethodName      = "/v10proto.base.v1.V10/DeleteVehicle"
	V10_UpdateVehicle_FullMethodName      = "/v10proto.base.v1.V10/UpdateVehicle"
	V10_UpdateUserMetadata_FullMethodName = "/v10proto.base.v1.V10/UpdateUserMetadata"
	V10_GetUserMetadata_FullMethodName    = "/v10proto.base.v1.V10/GetUserMetadata"
	V10_StartTrip_FullMethodName          = "/v10proto.base.v1.V10/StartTrip"
	V10_UpdateTrip_FullMethodName         = "/v10proto.base.v1.V10/UpdateTrip"
	V10_EndTrip_FullMethodName            = "/v10proto.base.v1.V10/EndTrip"
	V10_ListTrips_FullMethodName          = "/v10proto.base.v1.V10/ListTrips"
)

// V10Client is the client API for V10 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// V10 service definition.
type V10Client interface {
	// Testing endpoint.
	Do(ctx context.Context, in *DoRequest, opts ...grpc.CallOption) (*DoResponse, error)
	// Vehicle manual registration endpoint.
	RegisterVehicle(ctx context.Context, in *RegisterVehicleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// List vehicles owned by the user.
	ListVehicles(ctx context.Context, in *ListVehiclesRequest, opts ...grpc.CallOption) (V10_ListVehiclesClient, error)
	// Delete vehicle by VIN.
	DeleteVehicle(ctx context.Context, in *DeleteVehicleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Update vehicle by VIN.
	UpdateVehicle(ctx context.Context, in *UpdateVehicleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Update user metadata by id.
	UpdateUserMetadata(ctx context.Context, in *UpdateUserMetadataRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Get user metadata by id.
	GetUserMetadata(ctx context.Context, in *GetUserMetadataRequest, opts ...grpc.CallOption) (*GetUserMetadataResponse, error)
	// Start a trip.
	StartTrip(ctx context.Context, in *StartTripRequest, opts ...grpc.CallOption) (*StartTripResponse, error)
	// Update trip by id.
	UpdateTrip(ctx context.Context, in *UpdateTripRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// End a trip.
	EndTrip(ctx context.Context, in *EndTripRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// List trips.
	ListTrips(ctx context.Context, in *ListTripsRequest, opts ...grpc.CallOption) (V10_ListTripsClient, error)
}

type v10Client struct {
	cc grpc.ClientConnInterface
}

func NewV10Client(cc grpc.ClientConnInterface) V10Client {
	return &v10Client{cc}
}

func (c *v10Client) Do(ctx context.Context, in *DoRequest, opts ...grpc.CallOption) (*DoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DoResponse)
	err := c.cc.Invoke(ctx, V10_Do_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *v10Client) RegisterVehicle(ctx context.Context, in *RegisterVehicleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, V10_RegisterVehicle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *v10Client) ListVehicles(ctx context.Context, in *ListVehiclesRequest, opts ...grpc.CallOption) (V10_ListVehiclesClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &V10_ServiceDesc.Streams[0], V10_ListVehicles_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &v10ListVehiclesClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type V10_ListVehiclesClient interface {
	Recv() (*Vehicle, error)
	grpc.ClientStream
}

type v10ListVehiclesClient struct {
	grpc.ClientStream
}

func (x *v10ListVehiclesClient) Recv() (*Vehicle, error) {
	m := new(Vehicle)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *v10Client) DeleteVehicle(ctx context.Context, in *DeleteVehicleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, V10_DeleteVehicle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *v10Client) UpdateVehicle(ctx context.Context, in *UpdateVehicleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, V10_UpdateVehicle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *v10Client) UpdateUserMetadata(ctx context.Context, in *UpdateUserMetadataRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, V10_UpdateUserMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *v10Client) GetUserMetadata(ctx context.Context, in *GetUserMetadataRequest, opts ...grpc.CallOption) (*GetUserMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserMetadataResponse)
	err := c.cc.Invoke(ctx, V10_GetUserMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *v10Client) StartTrip(ctx context.Context, in *StartTripRequest, opts ...grpc.CallOption) (*StartTripResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartTripResponse)
	err := c.cc.Invoke(ctx, V10_StartTrip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *v10Client) UpdateTrip(ctx context.Context, in *UpdateTripRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, V10_UpdateTrip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *v10Client) EndTrip(ctx context.Context, in *EndTripRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, V10_EndTrip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *v10Client) ListTrips(ctx context.Context, in *ListTripsRequest, opts ...grpc.CallOption) (V10_ListTripsClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &V10_ServiceDesc.Streams[1], V10_ListTrips_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &v10ListTripsClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type V10_ListTripsClient interface {
	Recv() (*Trip, error)
	grpc.ClientStream
}

type v10ListTripsClient struct {
	grpc.ClientStream
}

func (x *v10ListTripsClient) Recv() (*Trip, error) {
	m := new(Trip)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// V10Server is the server API for V10 service.
// All implementations must embed UnimplementedV10Server
// for forward compatibility
//
// V10 service definition.
type V10Server interface {
	// Testing endpoint.
	Do(context.Context, *DoRequest) (*DoResponse, error)
	// Vehicle manual registration endpoint.
	RegisterVehicle(context.Context, *RegisterVehicleRequest) (*emptypb.Empty, error)
	// List vehicles owned by the user.
	ListVehicles(*ListVehiclesRequest, V10_ListVehiclesServer) error
	// Delete vehicle by VIN.
	DeleteVehicle(context.Context, *DeleteVehicleRequest) (*emptypb.Empty, error)
	// Update vehicle by VIN.
	UpdateVehicle(context.Context, *UpdateVehicleRequest) (*emptypb.Empty, error)
	// Update user metadata by id.
	UpdateUserMetadata(context.Context, *UpdateUserMetadataRequest) (*emptypb.Empty, error)
	// Get user metadata by id.
	GetUserMetadata(context.Context, *GetUserMetadataRequest) (*GetUserMetadataResponse, error)
	// Start a trip.
	StartTrip(context.Context, *StartTripRequest) (*StartTripResponse, error)
	// Update trip by id.
	UpdateTrip(context.Context, *UpdateTripRequest) (*emptypb.Empty, error)
	// End a trip.
	EndTrip(context.Context, *EndTripRequest) (*emptypb.Empty, error)
	// List trips.
	ListTrips(*ListTripsRequest, V10_ListTripsServer) error
	mustEmbedUnimplementedV10Server()
}

// UnimplementedV10Server must be embedded to have forward compatible implementations.
type UnimplementedV10Server struct {
}

func (UnimplementedV10Server) Do(context.Context, *DoRequest) (*DoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Do not implemented")
}
func (UnimplementedV10Server) RegisterVehicle(context.Context, *RegisterVehicleRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterVehicle not implemented")
}
func (UnimplementedV10Server) ListVehicles(*ListVehiclesRequest, V10_ListVehiclesServer) error {
	return status.Errorf(codes.Unimplemented, "method ListVehicles not implemented")
}
func (UnimplementedV10Server) DeleteVehicle(context.Context, *DeleteVehicleRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteVehicle not implemented")
}
func (UnimplementedV10Server) UpdateVehicle(context.Context, *UpdateVehicleRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateVehicle not implemented")
}
func (UnimplementedV10Server) UpdateUserMetadata(context.Context, *UpdateUserMetadataRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserMetadata not implemented")
}
func (UnimplementedV10Server) GetUserMetadata(context.Context, *GetUserMetadataRequest) (*GetUserMetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserMetadata not implemented")
}
func (UnimplementedV10Server) StartTrip(context.Context, *StartTripRequest) (*StartTripResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartTrip not implemented")
}
func (UnimplementedV10Server) UpdateTrip(context.Context, *UpdateTripRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTrip not implemented")
}
func (UnimplementedV10Server) EndTrip(context.Context, *EndTripRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EndTrip not implemented")
}
func (UnimplementedV10Server) ListTrips(*ListTripsRequest, V10_ListTripsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListTrips not implemented")
}
func (UnimplementedV10Server) mustEmbedUnimplementedV10Server() {}

// UnsafeV10Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to V10Server will
// result in compilation errors.
type UnsafeV10Server interface {
	mustEmbedUnimplementedV10Server()
}

func RegisterV10Server(s grpc.ServiceRegistrar, srv V10Server) {
	s.RegisterService(&V10_ServiceDesc, srv)
}

func _V10_Do_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(V10Server).Do(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: V10_Do_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(V10Server).Do(ctx, req.(*DoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _V10_RegisterVehicle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterVehicleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(V10Server).RegisterVehicle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: V10_RegisterVehicle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(V10Server).RegisterVehicle(ctx, req.(*RegisterVehicleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _V10_ListVehicles_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListVehiclesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(V10Server).ListVehicles(m, &v10ListVehiclesServer{ServerStream: stream})
}

type V10_ListVehiclesServer interface {
	Send(*Vehicle) error
	grpc.ServerStream
}

type v10ListVehiclesServer struct {
	grpc.ServerStream
}

func (x *v10ListVehiclesServer) Send(m *Vehicle) error {
	return x.ServerStream.SendMsg(m)
}

func _V10_DeleteVehicle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVehicleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(V10Server).DeleteVehicle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: V10_DeleteVehicle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(V10Server).DeleteVehicle(ctx, req.(*DeleteVehicleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _V10_UpdateVehicle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateVehicleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(V10Server).UpdateVehicle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: V10_UpdateVehicle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(V10Server).UpdateVehicle(ctx, req.(*UpdateVehicleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _V10_UpdateUserMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(V10Server).UpdateUserMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: V10_UpdateUserMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(V10Server).UpdateUserMetadata(ctx, req.(*UpdateUserMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _V10_GetUserMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(V10Server).GetUserMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: V10_GetUserMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(V10Server).GetUserMetadata(ctx, req.(*GetUserMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _V10_StartTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartTripRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(V10Server).StartTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: V10_StartTrip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(V10Server).StartTrip(ctx, req.(*StartTripRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _V10_UpdateTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTripRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(V10Server).UpdateTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: V10_UpdateTrip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(V10Server).UpdateTrip(ctx, req.(*UpdateTripRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _V10_EndTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndTripRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(V10Server).EndTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: V10_EndTrip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(V10Server).EndTrip(ctx, req.(*EndTripRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _V10_ListTrips_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListTripsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(V10Server).ListTrips(m, &v10ListTripsServer{ServerStream: stream})
}

type V10_ListTripsServer interface {
	Send(*Trip) error
	grpc.ServerStream
}

type v10ListTripsServer struct {
	grpc.ServerStream
}

func (x *v10ListTripsServer) Send(m *Trip) error {
	return x.ServerStream.SendMsg(m)
}

// V10_ServiceDesc is the grpc.ServiceDesc for V10 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var V10_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v10proto.base.v1.V10",
	HandlerType: (*V10Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Do",
			Handler:    _V10_Do_Handler,
		},
		{
			MethodName: "RegisterVehicle",
			Handler:    _V10_RegisterVehicle_Handler,
		},
		{
			MethodName: "DeleteVehicle",
			Handler:    _V10_DeleteVehicle_Handler,
		},
		{
			MethodName: "UpdateVehicle",
			Handler:    _V10_UpdateVehicle_Handler,
		},
		{
			MethodName: "UpdateUserMetadata",
			Handler:    _V10_UpdateUserMetadata_Handler,
		},
		{
			MethodName: "GetUserMetadata",
			Handler:    _V10_GetUserMetadata_Handler,
		},
		{
			MethodName: "StartTrip",
			Handler:    _V10_StartTrip_Handler,
		},
		{
			MethodName: "UpdateTrip",
			Handler:    _V10_UpdateTrip_Handler,
		},
		{
			MethodName: "EndTrip",
			Handler:    _V10_EndTrip_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListVehicles",
			Handler:       _V10_ListVehicles_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListTrips",
			Handler:       _V10_ListTrips_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "base/v1/v10.proto",
}
