// Copyright 2017 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: google/iam/v1/logging/audit_data.proto

package logging

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	v1 "google.golang.org/genproto/googleapis/iam/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Audit log information specific to Cloud IAM. This message is serialized
// as an `Any` type in the `ServiceData` message of an
// `AuditLog` message.
type AuditData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Policy delta between the original policy and the newly set policy.
	PolicyDelta   *v1.PolicyDelta `protobuf:"bytes,2,opt,name=policy_delta,json=policyDelta,proto3" json:"policy_delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditData) Reset() {
	*x = AuditData{}
	mi := &file_google_iam_v1_logging_audit_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditData) ProtoMessage() {}

func (x *AuditData) ProtoReflect() protoreflect.Message {
	mi := &file_google_iam_v1_logging_audit_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditData.ProtoReflect.Descriptor instead.
func (*AuditData) Descriptor() ([]byte, []int) {
	return file_google_iam_v1_logging_audit_data_proto_rawDescGZIP(), []int{0}
}

func (x *AuditData) GetPolicyDelta() *v1.PolicyDelta {
	if x != nil {
		return x.PolicyDelta
	}
	return nil
}

var File_google_iam_v1_logging_audit_data_proto protoreflect.FileDescriptor

const file_google_iam_v1_logging_audit_data_proto_rawDesc = "" +
	"\n" +
	"&google/iam/v1/logging/audit_data.proto\x12\x15google.iam.v1.logging\x1a\x1cgoogle/api/annotations.proto\x1a\x1agoogle/iam/v1/policy.proto\"J\n" +
	"\tAuditData\x12=\n" +
	"\fpolicy_delta\x18\x02 \x01(\v2\x1a.google.iam.v1.PolicyDeltaR\vpolicyDeltaB\x89\x01\n" +
	"\x19com.google.iam.v1.loggingB\x0eAuditDataProtoP\x01Z<google.golang.org/genproto/googleapis/iam/v1/logging;logging\xaa\x02\x1bGoogle.Cloud.Iam.V1.Loggingb\x06proto3"

var (
	file_google_iam_v1_logging_audit_data_proto_rawDescOnce sync.Once
	file_google_iam_v1_logging_audit_data_proto_rawDescData []byte
)

func file_google_iam_v1_logging_audit_data_proto_rawDescGZIP() []byte {
	file_google_iam_v1_logging_audit_data_proto_rawDescOnce.Do(func() {
		file_google_iam_v1_logging_audit_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_google_iam_v1_logging_audit_data_proto_rawDesc), len(file_google_iam_v1_logging_audit_data_proto_rawDesc)))
	})
	return file_google_iam_v1_logging_audit_data_proto_rawDescData
}

var file_google_iam_v1_logging_audit_data_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_google_iam_v1_logging_audit_data_proto_goTypes = []any{
	(*AuditData)(nil),      // 0: google.iam.v1.logging.AuditData
	(*v1.PolicyDelta)(nil), // 1: google.iam.v1.PolicyDelta
}
var file_google_iam_v1_logging_audit_data_proto_depIdxs = []int32{
	1, // 0: google.iam.v1.logging.AuditData.policy_delta:type_name -> google.iam.v1.PolicyDelta
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_google_iam_v1_logging_audit_data_proto_init() }
func file_google_iam_v1_logging_audit_data_proto_init() {
	if File_google_iam_v1_logging_audit_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_iam_v1_logging_audit_data_proto_rawDesc), len(file_google_iam_v1_logging_audit_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_iam_v1_logging_audit_data_proto_goTypes,
		DependencyIndexes: file_google_iam_v1_logging_audit_data_proto_depIdxs,
		MessageInfos:      file_google_iam_v1_logging_audit_data_proto_msgTypes,
	}.Build()
	File_google_iam_v1_logging_audit_data_proto = out.File
	file_google_iam_v1_logging_audit_data_proto_goTypes = nil
	file_google_iam_v1_logging_audit_data_proto_depIdxs = nil
}
